name: defo
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.18
  - imageio=2.6.1
  - glob2=0.7
  - cmake=3.14.0
  - pybind11=2.4.3
  - click
  - matplotlib
  - joblib
  - Pillow=7
  - plotly=3
  - pip:
    - gtimer
    - gym==0.14.0
    - moviepy
    - opencv-python==4.1.2.30
    - Shapely==1.6.4.post2
    - pyquaternion==0.9.5 
    - sk-video==1.1.10
